services:
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./site/wp-content:/var/www/html/wp-content
    ports:
      - '80:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: $db_host
      WORDPRESS_DB_USER: $db_user
      WORDPRESS_DB_PASSWORD: $db_password
      WORDPRESS_DB_NAME: $db_name
      WORDPRESS_TABLE_PREFIX: $db_table_prefix
      WORDPRESS_DEBUG: $wp_debug_mode
      DISABLED_PLUGINS: $wp_plugins_to_disable
  db:
    container_name: db
    image: mysql:8.0.36
    volumes:
      - ./database:/var/lib/mysql
      - ./mysqldumps/backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - ./init/migrate.sh:/docker-entrypoint-initdb.d/migrate.sh
    command: ["sh", "-c", "chmod 777 /docker-entrypoint-initdb.d/migrate.sh && docker-entrypoint.sh mysqld"]
    restart: always
    ports: 
      - '3306:3306'
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: $db_root_password
      MYSQL_DATABASE: $db_name
      MYSQL_USER: $db_user
      MYSQL_PASSWORD: $db_password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      WORDPRESS_TABLE_PREFIX: $db_table_prefix
      PRODUCTION_URL: $production_url
  
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8080:8080'
